/*
 FireShot - Webpage Screenshots and Annotations
 Copyright (C) 2007-2020 Evgeny Suslikov (evgeny@suslikov.ru)
*/
var scriptLoaded=!0,stubbornNodes=[],modifiedNodes2=[],commPortName,options,sbStyle,lockedScrollEvent,ignoredAttributeFlagName="__fireshotIgnoredElement",prevPosXFlagName="__fireshotPosX",prevPosYFlagName="__fireshotPosY",analysisCountName="__fireshotCheckedCntr",fNative;chrome.runtime.sendMessage&&chrome.runtime.sendMessage({message:"getPortName"},function(a){commPortName=a.portName;getConsolePtr()("Obtained port name: "+commPortName)});function getOptionFromScript(a,e){return options[a]||e}
function enableSomeElements(a){"undefined"===typeof a&&(a=!0);var e;if(window.location.href.match(/https?:\/\/mail\.google\.com/i)){for(var d=document.createNodeIterator(document.body,NodeFilter.SHOW_ELEMENT,null,!1),g;g=d.nextNode();)"TD"==g.nodeName&&g.getAttribute("class")&&g.getAttribute("class").match(/Bu y3/i)&&g.style.setProperty("display",a?"":"none","important");(e=document.getElementById(":ro"))&&e.style.setProperty("display",a?"":"none","important");(e=document.getElementById(":5"))&&e.style.setProperty("display",
a?"":"none","important")}}
function hideObtrusiveElements(a,e){for(var d=a.getBoundingClientRect(),g=window.innerWidth*window.innerHeight+1,q=d.width*d.height+1,k=document.createNodeIterator(document.body,NodeFilter.SHOW_ELEMENT,null,!1),f=a!==getScrollingElement(),n=.9*window.innerWidth,l=.9*window.innerHeight,u=.33*d.width,t=.33*d.height;null!==(d=k.nextNode());)if("1"!==d.getAttribute(ignoredAttributeFlagName)){var h="undefined"!==typeof d[analysisCountName]?d[analysisCountName]:0;if(!(2<h))if(d[analysisCountName]=++h,h=
d.getBoundingClientRect(),d.scrollWidth>n&&d.scrollHeight>l&&d.clientWidth>u&&d.clientHeight>t)d.setAttribute(ignoredAttributeFlagName,"1");else{var v=h.width*h.height;if(0===v||.35<v/g)d.setAttribute(ignoredAttributeFlagName,"1");else{v=d.getAttribute(prevPosXFlagName);var E=d.getAttribute(prevPosYFlagName);if(void 0===v)d.setAttribute(prevPosXFlagName,h.left),d.getAttribute(prevPosYFlagName,h.top);else if(!(!(!e&&E==h.top||e&&v==h.left)||elementInHiddenList(d)||d===a||f&&isChildOf(d,a)||f&&isChildOf(a,
d)&&.35<h.width*h.height/q)){a:{for(h=d;h&&h!=document;){v=document.defaultView.getComputedStyle(h,"");if("hidden"===v.visibility||"none"===v.display||"0"===v.opacity){h=!0;break a}h=h.parentNode}h=!1}h?d.setAttribute(ignoredAttributeFlagName,"1"):hideElement(d)}}}}}function elementInHiddenList(a){for(var e=0;e<stubbornNodes.length;++e)if(stubbornNodes[e].elem===a)return!0;return!1}
function hideElement(a){getConsolePtr()("Hiding:");getConsolePtr()(a);stubbornNodes.push({elem:a,opacity:a.style.getPropertyValue("opacity"),animation:a.style.getPropertyValue("animation"),transitionDuration:a.style.getPropertyValue("transition-duration")});a.style.setProperty("opacity","0");a.style.setProperty("animation","unset");a.style.setProperty("transition-duration","0s");a.setAttribute(ignoredAttributeFlagName,"1")}
function hideStubbornElements(a,e){var d=a?a.getBoundingClientRect():void 0,g=d?d.width:window.innerWidth;d=d?d.height:window.innerHeight;e=e||!1;for(var q=document.createNodeIterator(document.body,NodeFilter.SHOW_ELEMENT,null,!1),k;k=q.nextNode();){var f=document.defaultView.getComputedStyle(k,"");!f||"fixed"!=f.getPropertyValue("position")&&"sticky"!=f.getPropertyValue("position")||elementInHiddenList(k)||"none"==f.getPropertyValue("display")||a&&isChildOf(k,a)||e&&k.scrollWidth>window.innerWidth||
k.scrollWidth>.9*window.innerWidth&&k.scrollHeight>.9*window.innerHeight&&k.clientWidth>.33*g&&k.clientHeight>.33*d||(getConsolePtr()("Found stubborn element "+k.id),hideElement(k))}for(a=0;a<stubbornNodes.length;++a)stubbornNodes[a].elem.style.setProperty("opacity","0")}
function showHiddenElements(){for(var a=0;a<stubbornNodes.length;++a)stubbornNodes[a].elem.style.setProperty("opacity",stubbornNodes[a].opacity),stubbornNodes[a].elem.style.setProperty("animation",stubbornNodes[a].animation),stubbornNodes[a].elem.style.setProperty("transition-duration",stubbornNodes[a].transitionDuration)}
function removeCustomAttributes(){for(var a=document.createNodeIterator(document.body,NodeFilter.SHOW_ELEMENT,null,!1),e;e=a.nextNode();)e.removeAttribute(ignoredAttributeFlagName),e.removeAttribute(prevPosXFlagName),e.removeAttribute(prevPosYFlagName),"undefined"!==typeof e[analysisCountName]&&delete e[analysisCountName]}
function FBAdapter(){var a=[];(function(){a=Array.prototype.slice.call(document.querySelectorAll("DIV")).map(function(a){return{element:a,top:a.style.top}}).filter(function(a){return"absolute"==a.element.style.position})})();return{undoSwitchingToFixedPositions:function(){a.forEach(function(a){"fixed"==a.element.style.position&&(a.element.style.position="absolute",a.element.style.top=a.top)})}}}
function getAltExtents(){var a=window.document,e=a.documentElement;e=e.clientWidth?e.clientWidth:window.innerWidth;var d=-1;0>d&&(d=window.innerHeight-getSBHeight(window));if(a.body){var g="CSS1Compat"==a.compatMode?a.documentElement.scrollWidth:a.body.scrollWidth,q=a.documentElement.scrollHeight,k="CSS1Compat"==a.compatMode?a.documentElement.clientWidth:a.body.clientWidth;a="CSS1Compat"==a.compatMode?a.documentElement.clientHeight:a.body.clientHeight;g<k&&(g=k);q<a&&(q=a);e<g&&(e=g);d<q&&(d=q)}return{Width:e,
Height:d}}
function findScrolledElement(a,e){for(var d=document,g,q=location.href,k=document.createNodeIterator(document.body,NodeFilter.SHOW_ELEMENT,null,!1),f;null!==(f=k.nextNode());)if(0<f.scrollWidth&&0<f.scrollHeight&&(f.scrollWidth>f.clientWidth||f.scrollHeight>f.clientHeight)&&(q.match(/https?:\/\/www\.(facebook|fb)\.com/i)&&f.scrollHeight>.5*e||f.scrollWidth>a&&f.scrollHeight>.5*e||f.scrollHeight>e&&f.scrollWidth>.3*a||f.clientWidth>.7*a&&f.clientHeight>.7*e)){var n=d.defaultView.getComputedStyle(f,"");
isScrollableStyle(n)&&(!g||g.scrollWidth*g.scrollHeight<f.scrollWidth*f.scrollHeight)&&(n=getElementExtents(f),n.absoluteX+n.w<=window.innerWidth+2&&(n.absoluteY+n.h<=window.innerHeight+2||1.5*window.innerHeight<f.scrollHeight&&f.clientHeight<=window.innerHeight+50)&&(!g||g.scrollWidth*g.scrollHeight<f.scrollWidth*f.scrollHeight)&&(g=f))}g&&(getConsolePtr()("Found scrolled element:"),getConsolePtr()(g));return g}
function getElementExtents(a){var e=a.getClientRects(),d={absoluteX:0,absoluteY:0,x:0,y:0,w:0,h:0};0<e.length&&(d.absoluteX=a.clientLeft+e[0].left,d.absoluteY=a.clientTop+e[0].top,d.w=e[0].width,d.h=e[0].height);return d}
function disableFloatingInView(a){var e=document,d=getElementExtents(a),g=window.innerWidth*window.innerHeight+1;modifiedNodes2=[];for(var q=e.createNodeIterator(e.body,NodeFilter.SHOW_ELEMENT,null,!1),k;null!==(k=q.nextNode());){var f=e.defaultView.getComputedStyle(k,"");if(f&&"0"!==f.getPropertyValue("opacity")&&("absolute"==f.getPropertyValue("position")||"relative"==f.getPropertyValue("position"))){var n=getElementExtents(k);0===n.w*n.h||.35<n.w*n.h/g||k==a||!getIntersection(d.absoluteX,d.absoluteY,
d.w,d.h,n.absoluteX,n.absoluteY,n.w,n.h)||isChildOf(a,k)||isChildOf(k,a)||(getConsolePtr()("Hiding:"),getConsolePtr()(k),modifiedNodes2.push({object:k,opacity:f.getPropertyValue("opacity")}),k.style.setProperty("opacity","0","important"))}}}function disableScrollEvent(){lockedScrollEvent=function(a){a.stopImmediatePropagation()};window.addEventListener("scroll",lockedScrollEvent,!0)}function enableScrollEvent(){window.removeEventListener("scroll",lockedScrollEvent,!0)}
function enableFloatingInView(){for(var a=0;a<this.modifiedNodes2.length;a++)modifiedNodes2[a].object.style.setProperty("opacity",modifiedNodes2[a].opacity)}function getOffsets(a,e,d){var g={x:0,y:0};e===cModeVisible?(g.x=getScrollingElement().scrollLeft,g.y=getScrollingElement().scrollTop):e===cModeSelected?(g.x=d.left,g.y=d.top):a.div&&(g.x=a.left,g.y=a.top);return g}function getScrollingElement(){return document.scrollingElement||document.body}
chrome.runtime.onConnect.addListener(function(a){function e(b,d){options[b]=d;a.postMessage({topic:"setOption",optionName:b,optionValue:d})}function d(a,d){m=d;l=a;b=getScrollingElement();l!=cModeEntire||m||q||(m=findScrolledElement(b.scrollWidth,b.scrollHeight));x=m||G.body;m&&(b=m,m.scrollIntoView(),disableFloatingInView(m),Q=m.style.zIndex,m.style.zIndex=2147483647);R=b.scrollTop;S=b.scrollLeft;y=b.scrollWidth;z=b.scrollHeight;F=H=I=void 0;if(!m){"hidden"===document.defaultView.getComputedStyle(document.body,
"").overflowX&&(F=x.style.overflowX,a=b.scrollHeight,x.style.overflowX="visible",a>=b.scrollHeight&&(x.style.overflowX=F,F=void 0));y=Math.max(G.documentElement.scrollWidth,x.scrollWidth,document.documentElement.clientWidth,x.offsetWidth,document.documentElement.offsetWidth);z=Math.max(G.documentElement.scrollHeight,x.scrollHeight,document.documentElement.clientHeight,x.offsetHeight,document.documentElement.offsetHeight);if(0>=y||0>=z)a=getAltExtents(),y=a.Width,z=a.Height;0>=y&&(y=1024);0>=z&&(z=
768)}l===cModeEntire&&(k?(b.scrollTop=1,b.scrollLeft=1,setTimeout(function(){b.scrollTop=0;b.scrollLeft=0},10)):(b.scrollTop=0,b.scrollLeft=0));J&&(T=FBAdapter());l!==cModeVisible&&l!==cModeBrowser&&enableSomeElements(!1);m?(D=m.clientWidth,B=m.clientHeight):(D=window.innerWidth,B=window.innerHeight,y<window.innerWidth&&(y=window.innerWidth))}if(chrome.runtime.sendMessage&&a.name!=commPortName)getConsolePtr()("Comm port name is wrong: "+a.name+" <> "+commPortName);else{var g=!0,q=!1,k=0===window.navigator.plugins.length&&
isConsoleOpened(),f=1,n=1,l=0,u=0,t=1,h=1,v=!0,E=!0,D=0,B=0,K=0,M=0,U=0,V=0,p={left:0,top:0,right:0,bottom:0},m,G,x,b,R,S,W,N,L,F,I,H,O,y,z,Q,X,A,J=window.location.href.match(/https?:\/\/www\.(facebook|fb)\.com/i),T;stubbornNodes=[];modifiedNodes2=[];a.onMessage.addListener(function(c){switch(c.topic){case "init":X=c.p;fNative=c.native;window.isDebug|=c.debug;u=X?150:200;G=window.document;options=JSON.parse(c.options);q=c.frameMode;try{d(c.mode)}catch(Y){getConsolePtr()(Y.toString());a.postMessage({topic:"initAborted"});
return}O=document.defaultView.getComputedStyle(document.documentElement,"").scrollBehavior;""!=O&&(document.documentElement.style.scrollBehavior="initial");J||disableScrollEvent();if(l!==cModeSelected&&!m||k){W=!0;N=b.style.overflow;L=b.style.height;var r=b.scrollHeight;b.style.overflow="hidden";b.style.height=z+"px";b.scrollHeight!=r&&(0<r&&1.1<b.scrollHeight/r||0<b.scrollHeight&&1.1<r/b.scrollHeight)&&(b.style.height=L,L=void 0);b.scrollHeight!=r&&(0<r&&1.1<b.scrollHeight/r||0<b.scrollHeight&&1.1<
r/b.scrollHeight)&&(b.style.overflow=N);document.scrollingElement||(H=document.defaultView.getComputedStyle(document.documentElement,"").overflowY,document.documentElement.style.overflowY="initial",I=document.defaultView.getComputedStyle(document.documentElement,"").overflowX,document.documentElement.style.overflowX="initial")}var x={topic:"initDone",url:document.location.toString(),title:document.title,cw:q&&frameElement?frames.parent.innerWidth:window.innerWidth,ch:q&&frameElement?frames.parent.innerHeight:
window.innerHeight,emulation:k};J&&l===cModeEntire?setTimeout(function(){b.scrollTop=z;setTimeout(function(){b.scrollTop=0;setTimeout(function(){a.postMessage(x)},u)},u)},u):setTimeout(function(){a.postMessage(x)},u);break;case "setRatio":t=c.ratioW;h=c.ratioH;getConsolePtr()("Ratios: "+t+", "+h);break;case "selectArea":if(!document.body){alert("Apologies, this page does not support capturing selections.");a.postMessage({topic:"areaSelectionCanceled"});enableScrollEvent();break}hideStubbornElements();
var P=FireShotAddon.FSSelectionHint(document);fNative&&"false"!==getOptionFromScript(cShowSelectionHintPref,"true")&&P.show();FireShotAddon.FSSelector({browser:"chrome",extendedMode:fNative,doc:document}).makeSelection(function(c){fNative&&(P.isShown()?P.hide():e(cShowSelectionHintPref,"false"));c.left==c.right||c.top==c.bottom?(a.postMessage({topic:"areaSelectionCanceled"}),showHiddenElements(),removeCustomAttributes(),enableScrollEvent()):(c.isScrollable?(getConsolePtr()("Capturing element:"),getConsolePtr()(c.selectedElement),
d(cModeEntire,c.selectedElement)):(b.scrollLeft=c.left,b.scrollTop=c.top,K=b.scrollLeft,M=b.scrollTop,p.left=c.left,p.top=c.top,p.right=c.right,p.bottom=c.bottom),setTimeout(function(){hideStubbornElements();a.postMessage({topic:"areaSelected"})},u))});break;case "scrollNext":if(g){A=new LinksGrabber(m||document);A.clearAttributes();A.markHiddenLinks();A.createLinksSnapshot();hideObtrusiveElements(b,!1);0===b.scrollLeft&&0===b.scrollTop&&A.checkClickableLinks();g=!1;setTimeout(function(){a.postMessage({topic:"scrollDone",
x:b.scrollLeft*t,y:b.scrollTop*h})},u);return}if(v&&l!=cModeVisible&&l!=cModeBrowser){var Z=l==cModeSelected?p.right:y;var C=Math.max(D-30,0);var w=b.scrollLeft;b.scrollLeft+=Math.max(0,Math.min(C,Z-(b.scrollLeft+C)+20));if(v=b.scrollLeft!=w&&b.scrollLeft<y){1==f&&n++;getConsolePtr()("scrollLeft:"+b.scrollLeft);setTimeout(function(){hideStubbornElements(m,!0);hideObtrusiveElements(b,!0);A.createLinksSnapshot();setTimeout(function(){a.postMessage({topic:"scrollDone",x:b.scrollLeft*t,y:b.scrollTop*
h})},u)},0);return}l==cModeSelected&&(U=b.scrollLeft)}if(E&&l!=cModeVisible&&l!=cModeBrowser&&(C=0===b.scrollTop?B-150:B-40,0>=C&&(C=B),w=b.scrollTop,b.scrollTop+=Math.max(0,C),E=w!=b.scrollTop&&b.scrollTop<z,l==cModeSelected&&((E&=b.scrollTop<p.bottom)||(V=w)),E)){f++;b.scrollLeft=l==cModeEntire?0:K;getConsolePtr()("scrollTop:"+b.scrollTop);v=!0;setTimeout(function(){J&&T.undoSwitchingToFixedPositions();hideStubbornElements(m);hideObtrusiveElements(b,!1);A.createLinksSnapshot();setTimeout(function(){a.postMessage({topic:"scrollDone",
x:b.scrollLeft*t,y:b.scrollTop*h})},u)},u);return}c={topic:"scrollFinished",div:0,left:0,top:0,width:l==cModeEntire?y:D,height:l==cModeEntire?z:B,ratioW:t,ratioH:h,rows:f,cols:n,cw:D,ch:B,hScrollbar:window.innerHeight>B,vScrollBar:window.innerWidth>D,cropLeft:0,cropRight:0,cropTop:0,cropBottom:0};q&&frameElement?(c.div=1,c.left=frameElement.clientLeft+frameElement.offsetLeft,c.top=frameElement.clientTop+frameElement.offsetTop):m&&(w=m.getClientRects(),c.div=1,0<w.length&&(c.left=m.clientLeft+w[0].left,
c.top=m.clientTop+w[0].top),m.style.zIndex=Q,enableFloatingInView());l===cModeSelected&&(c.width=U-K+D,c.height=V-M+B,c.crop=!0,c.cropLeft=p.left-K,c.cropTop=p.top-M,c.cropRight=c.cropLeft+(p.right-p.left),c.cropBottom=c.cropTop+(p.bottom-p.top));getConsolePtr()(JSON.stringify(c));w=getOffsets(c,l,p);A.getLinks(c,w);A.clearAttributes();A=void 0;b.scrollLeft=0;b.scrollTop=0;l===cModeSelected?r=new fsRect(p.left,p.top,p.right-p.left,p.bottom-p.top):l===cModeVisible&&(r=new fsRect(w.x,w.y,c.width,c.height));
C=new TextGrabber(b);c.words=C.getElements(w,t,h,r);c.left*=t;c.top*=h;c.width*=t;c.height*=h;c.cw*=t;c.ch*=h;c.cropLeft*=t;c.cropTop*=h;c.cropRight*=t;c.cropBottom*=h;b.scrollLeft=S;b.scrollTop=R;document.documentElement.style.scrollBehavior=O;W&&(b.style.overflow=N,b.style.height=L);void 0!==F&&(document.body.style.overflowX=F);void 0!==H&&(document.documentElement.style.overflowY=H);void 0!==I&&(document.documentElement.style.overflowX=I);enableScrollEvent();l!=cModeVisible&&l!=cModeBrowser&&enableSomeElements(!0);
showHiddenElements();removeCustomAttributes();setTimeout(function(){a.postMessage(c)},u);break;case "sendFireShotCaptureCompleteEvent":window.fsPendingCB&&(r={cbId:window.fsPendingCB,data:c.data},"undefined"!==typeof cloneInto&&(r=cloneInto(r,document.defaultView)),r=new document.defaultView.CustomEvent("FireShotCaptureCompleteEvent",{detail:r}),document.dispatchEvent(r))}getConsolePtr()("CS:"+c.topic)})}});
