/*
 FireShot - Webpage Screenshots and Annotations
 Copyright (C) 2007-2020 Evgeny Suslikov (evgeny@suslikov.ru)
*/
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,l,g){a!=Array.prototype&&a!=Object.prototype&&(a[l]=g.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(l){return $jscomp.SYMBOL_PREFIX+(l||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var l=0;return $jscomp.iteratorPrototype(function(){return l<a.length?{done:!1,value:a[l++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.polyfill=function(a,l,g,m){if(l){g=$jscomp.global;a=a.split(".");for(m=0;m<a.length-1;m++){var n=a[m];n in g||(g[n]={});g=g[n]}a=a[a.length-1];m=g[a];l=l(m);l!=m&&null!=l&&$jscomp.defineProperty(g,a,{configurable:!0,writable:!0,value:l})}};
$jscomp.polyfill("Array.from",function(a){return a?a:function(a,g,m){$jscomp.initSymbolIterator();g=null!=g?g:function(b){return b};var n=[],d=a[Symbol.iterator];if("function"==typeof d)for(a=d.call(a);!(d=a.next()).done;)n.push(g.call(m,d.value));else{d=a.length;for(var c=0;c<d;c++)n.push(g.call(m,a[c]))}return n}},"es6","es3");
function fsRect(a,l,g,m){return{left:a,top:l,width:g,height:m,fromCSSClip:function(a){a=a.match(/\d+/g);4===a.length&&(this.left=a[3],this.top=a[0],this.width=a[1]-a[3],this.height=a[2]-a[0]);return this}}}
function LinksGrabber(a){var l=document,g=a==document?getScrollingElement():a,m=function(d){var c=l.defaultView.getComputedStyle(d,"");if(!c||"hidden"!==c.getPropertyValue("overflow")&&"hidden"!==c.getPropertyValue("overflow-y")&&"auto"!==c.getPropertyValue("overflow-y")&&"scroll"!=c.getPropertyValue("overflow-y")&&"hidden"!==c.getPropertyValue("overflow-x")&&"auto"!==c.getPropertyValue("overflow-x")&&"scroll"!=c.getPropertyValue("overflow-x"))return n(d.children[0],a)},n=function(a,c){a=a.getBoundingClientRect();
return{top:Math.round(a.top+(window.pageYOffset||g.scrollTop)),left:Math.round(a.left+(window.pageXOffset||g.scrollLeft)),width:a.width,height:a.height}};return{collectedLinks:[],markHiddenLinks:function(){for(var d=[],c=l.createNodeIterator(a==document?a.body:a,NodeFilter.SHOW_ELEMENT,null,!1),b;b=c.nextNode();)if(b.childElementCount&&"HTML"!==b.tagName&&"BODY"!==b.tagName&&b!==a&&(b.offsetHeight<b.scrollHeight||b.offsetWidth<b.scrollWidth)){var e=l.defaultView.getComputedStyle(b,"");!e||"none"===
e.getPropertyValue("display")||"hidden"!==e.getPropertyValue("overflow")&&"hidden"!==e.getPropertyValue("overflow-y")&&"auto"!==e.getPropertyValue("overflow-y")&&"scroll"!=e.getPropertyValue("overflow-y")&&"hidden"!==e.getPropertyValue("overflow-x")&&"auto"!==e.getPropertyValue("overflow-x")&&"scroll"!=e.getPropertyValue("overflow-x")||d.push(b)}d.forEach(function(b){var e=n(b,a);b=b.getElementsByTagName("a");for(var d=0,f=0;f<b.length;++f){var r=b[f],c=n(r,a);rectsIntersected(e,c)||(r.setAttribute("__fireshotHiddenLink",
1),++d)}})},createLinksSnapshot:function(){function d(b){if(b.getAttribute("__fireshotHiddenLink"))return!1;var a;if(a=b.href&&""!==b.href&&!/javascript:.*/.test(b.href)&&b.href.slice&&"#"!==b.href.slice(-1)){a:{for(;b&&b!=l;){a=l.defaultView.getComputedStyle(b,"");if("hidden"===a.visibility||"none"===a.display||"0"===a.opacity){b=!0;break a}b=b.parentNode}b=!1}a=!b}return a}function c(b,e){var h=n(b,a),d=Array.from(b.getClientRects());if(1===d.length){var f;b.children&&0<b.children.length&&"IMG"===
b.children[0].tagName&&(f=m(b))&&0<f.width&&0<f.height?e.push(f):e.push(h)}else if(b.children&&0<b.children.length)for(d=[],d=0;d<b.children.length;d++)h=n(b.children[d]),0<h.width&&0<h.height&&e.push(h);else{d=d.filter(function(b){return 0<b.width&&0<b.height});for(b=0;b<d.length;++b)if(0===b)var c={left:d[b].left,top:d[b].top};else d[b].left<c.left&&(c.left=d[b].left),d[b].top<c.top&&(c.top=d[b].top);if(c)for(f=h.left-c.left,h=h.top-c.top,b=0;b<d.length;++b)e.push({left:d[b].left+f,top:d[b].top+
h,width:d[b].width,height:d[b].height})}}for(var b=a.getElementsByTagName("a"),e={left:0,top:0,width:window.innerWidth,height:window.innerHeight},f=0;f<b.length;++f){var h=b[f],k=!fNative&&d(h);if(rectsIntersected(h.getBoundingClientRect(),e)&&(k||d(h))&&(k=[],c(h,k),0!==k.length)){var g=h.getAttribute("__fireshotLinkId");g?g=parseInt(g):(g=this.collectedLinks.length,h.setAttribute("__fireshotLinkId",g));this.collectedLinks[g]={e:h,r:k}}}},getLinks:function(a,c){var b=a.crop?a.cropRight-a.cropLeft:
a.width,e=a.crop?a.cropBottom-a.cropTop:a.height;a.links=[];for(var d=0;d<this.collectedLinks.length;++d){var h=this.collectedLinks[d],k=this.collectedLinks[d].e;if(!k.getAttribute("__fireshotHiddenLink")){for(var g=[],l=0;l<h.r.length;++l){var p=h.r[l].left-c.x,m=h.r[l].top-c.y,q=h.r[l].width,n=h.r[l].height;p>=b||m>=e||(0>p&&(q+=p,p=0),0>m&&(n+=m,m=0),p+q>b&&(q=b-p),m+n>e&&(n=e-m),0<q&&0<n&&g.push([Math.round(p*a.ratioW),Math.round(m*a.ratioH),Math.round(q*a.ratioW),Math.round(n*a.ratioH)]))}0<
g.length&&a.links.push({a:k.href,r:g,h:""})}}getConsolePtr()("links filtered: "+(this.collectedLinks.length-a.links.length));getConsolePtr()("links added: "+a.links.length)},checkClickableLinks:function(){for(var a,c,b=g.scrollLeft,e=g.scrollTop,f=0;f<this.collectedLinks.length;++f)if(!this.collectedLinks[f].p){a=this.collectedLinks[f].r[0].left-b;c=this.collectedLinks[f].r[0].top-e;0>a&&(a+=this.collectedLinks[f].r[0].width);0>c&&(c+=this.collectedLinks[f].r[0].height);var h;0<=c&&c<=window.innerHeight&&
0<=a&&a<=window.innerWidth&&((h=document.elementFromPoint(Math.round(a+.5),Math.round(c+.5)))===this.collectedLinks[f].e||h&&this.collectedLinks[f].e.contains(h)||this.collectedLinks[f].e.setAttribute("__fireshotHiddenLink",1))}},clearAttributes:function(){for(var d=a.getElementsByTagName("a"),c=0;c<d.length;++c)d[c].removeAttribute("__fireshotHiddenLink"),d[c].removeAttribute("__fireshotLinkId")}}}
function TextGrabber(a){function l(b,a){function e(b){function a(a,e){function c(a,e,c,d){var f=new Range;f.setStart(b,a);f.setEnd(b,e);a=f.getClientRects();e=[];if(d)for(f=0;f<a.length;++f){var k=n(a[f],d);if(0<k.width&&0<k.height){e.push(k);break}}else e=a;0<e.length&&h.push({t:c,r:[Math.floor(e[0].left),Math.floor(e[0].top),Math.ceil(e[0].width),Math.ceil(e[0].height)]})}var d=a,f=b.textContent;if("undefined"!==typeof b.fsOverflowRect)var g=b.fsOverflowRect;for(;d<a+e;){if(""===f[d].trim()){if(void 0!==
k){c(k,d,f.substr(k,d-k),g);var k=void 0}}else void 0===k&&(k=d);++d}void 0!==k&&c(k,a+e,f.substr(k,e-(k-a)),g)}(function(){var a=new Range,e=[],c=b.textContent.length;a.setStart(b,0);a.setEnd(b,c);a=a.getClientRects();if(1===a.length)return[{o:0,l:c}];var d=0,h=1,f=a.length;a=new Range;for(a.setStart(b,d);1<f&&h<c;){a.setEnd(b,h+1);var k=a.getClientRects();1<k.length&&k[0].y!=k[k.length-1].y&&(e.push({o:d,l:h-d}),d=h,a.setStart(b,d),--f);++h}e.push({o:d,l:c-d});return e})().forEach(function(b){return a(b.o,
b.l)})}for(var h=[],d=document.createTreeWalker(b,NodeFilter.SHOW_TEXT,null,!1);b=d.nextNode();)if(b.parentNode&&b.parentNode.getBoundingClientRect){var c=b.parentNode.getBoundingClientRect();if(c&&2<c.width&&2<c.height&&""!==b.textContent.trim()&&(!a||m(a,c))){c=document.defaultView.getComputedStyle(b.parentNode,"");if("rect"===c.clip.substr(0,4)&&"absolute"===c.position){var g=fsRect().fromCSSClip(c.clip);if(4>g.width||4>g.height)continue}"hidden"!==c.visibility&&"none"!==c.display&&"0"!==c.opacity&&
e(b)}}return h}function g(b){for(var a=[],d=document.createTreeWalker(b,NodeFilter.SHOW_ELEMENT,null,!1);b=d.nextNode();)if(b.getBoundingClientRect){var c;(c=!b.childElementCount||"HTML"===b.tagName||"BODY"===b.tagName)||(c=document.defaultView.getComputedStyle(b,""),c=!(c&&"none"!==c.getPropertyValue("display")&&("hidden"===c.getPropertyValue("overflow")||"hidden"===c.getPropertyValue("overflow-y")||"auto"===c.getPropertyValue("overflow-y")||"scroll"==c.getPropertyValue("overflow-y")||"hidden"===
c.getPropertyValue("overflow-x")||"auto"===c.getPropertyValue("overflow-x")||"scroll"==c.getPropertyValue("overflow-x"))));c||a.push(b)}return a}function m(b,a){return b.left<a.left+a.width&&a.left<b.left+b.width&&b.top<a.top+a.height&&a.top<b.top+b.height}function n(b,a){if(m(b,a)){var c=Math.max(b.left,a.left),d=Math.max(b.top,a.top);return new fsRect(c,d,Math.min(b.left+b.width,a.left+a.width)-c,Math.min(b.top+b.height,a.top+a.height)-d)}return new fsRect(0,0,0,0)}function d(a){for(var b=[],c=
0;c<a.length;++c){var d=a[c].getBoundingClientRect();var k=document.defaultView.getComputedStyle(a[c],"");walk=document.createTreeWalker(a[c],NodeFilter.SHOW_TEXT,null,!1);"inline"!==k.display&&(d.width=Math.min(d.width,a[c].clientWidth),d.height=Math.min(d.height,a[c].clientHeight));for(;k=walk.nextNode();)k.parentNode&&k.parentNode.getClientRects&&""!==k.textContent.trim()&&("undefined"!==typeof k.fsOverflowRect?k.fsOverflowRect=n(k.fsOverflowRect,d):(k.fsOverflowRect=d,b.push(k)))}return b}function c(){for(var b,
c=document.createTreeWalker(a,NodeFilter.SHOW_TEXT,null,!1);b=c.nextNode();)"undefined"!==typeof b.fsOverflowRect&&delete b.fsOverflowRect}return{doTests:function(){var a=document.createElement("canvas");a.id="helperCanvas";a.width=document.scrollingElement.scrollWidth-2;a.height=document.scrollingElement.scrollHeight-2;a.style.zIndex=2147483647;a.style.position="absolute";a.style.border="1px solid";a.style.left=0;a.style.top=0;a.style.pointerEvents="none";document.getElementsByTagName("body")[0].prepend(a);
a.getContext("2d");a=performance.now();var d=this.getElements({x:0,y:0},1,1,!1);console.log("Items in array a: "+d.length);console.log("JSON size: "+JSON.stringify(d).length);console.log("Time: "+Math.round(performance.now()-a)+"ms");console.log(d);c();return d},getElements:function(b,e,f,h){d(g(a));h=l(a,h);0==b.x&&0==b.y&&1==e&&1==f||h.forEach(function(a){a.r[0]-=b.x;a.r[1]-=b.y;a.r[0]*=e;a.r[1]*=f;a.r[2]*=e;a.r[3]*=f});c();return h}}};
