/*
 FireShot - Webpage Screenshots and Annotations
 Copyright (C) 2007-2020 Evgeny Suslikov (evgeny@suslikov.ru)
*/
var FireShotSettings={hkModifiers:"ctrl, alt",hkKey:"Z",hkKeyCode:0,loadSettings:function(){$("#edtDefaultFolder").val(getOption(cDefaultFolderPref,cDefaultFolderValue));$("#chkOpenFolder").prop("checked","true"===getOption(cOpenFolderAterSavingPref,"false"));$("#chkDoNotShowSaveAsDialog").prop("checked","true"===getOption(cNoFilenamePromptPref,"false"));$("#chkCloseTab").prop("checked","true"===getOption(cCloseTabAfterSaving,"false"));$("#edtFilenameTemplate").val(getOption(cTemplatePref,cDefaultTemplate));
$("#edtTemplateNumber").val(getOption(cTemplateNumberPref,1));$("#chkTemplateNumberPad").prop("checked","true"===getOption(cTemplateNumberPadCheckPref,"true"));$("#edtTemplateNumberPad").val(getOption(cTemplateNumberPadValuePref,3));var b="png"===getOption(cDefaultImageFormatPref,"png");$("#radImagePNG").prop("checked",b);$("#radImageJPG").prop("checked",!b);$("#edtTemplateFilenameMaxLen").val(getOption(cTemplateFilenameMaxLen,100));$("#chkContextMenuIntegration").prop("checked","true"===getOption(cContextMenuIntegrationPref,
"true"));$("#chkAPI").prop("checked","true"===getOption(cAPISupport,"false"))},saveSettings:function(b){localStorage[cTemplatePref]=$("#edtFilenameTemplate").val();localStorage[cTemplateNumberPref]=parseInt($("#edtTemplateNumber").val());localStorage[cTemplateNumberPadCheckPref]=$("#chkTemplateNumberPad").prop("checked");localStorage[cTemplateNumberPadValuePref]=Math.max(0,parseInt($("#edtTemplateNumberPad").val()));localStorage[cDefaultImageFormatPref]=$("#radImagePNG").prop("checked")?"png":"jpg";
localStorage[cTemplateFilenameMaxLen]=Math.max(10,parseInt($("#edtTemplateFilenameMaxLen").val()));localStorage[cDefaultFolderPref]=$("#edtDefaultFolder").val();localStorage[cNoFilenamePromptPref]=$("#chkDoNotShowSaveAsDialog").prop("checked");localStorage[cOpenFolderAterSavingPref]=$("#chkOpenFolder").prop("checked");localStorage[cCloseTabAfterSaving]=$("#chkCloseTab").prop("checked");localStorage[cContextMenuIntegrationPref]=$("#chkContextMenuIntegration").prop("checked");getExtension().updateContextMenu();
$("#chkAPI").prop("checked")?addTabsPermission(function(){enableAPI(!0);b&&b()},function(){alert("WARNING: FireShot API is NOT enabled.");enableAPI(!1);$("#chkAPI").prop("checked",!1);b&&b()}):(enableAPI(!1),b&&b())},processHotkey:function(b,a){a.preventDefault();a.stopPropagation();a=getShortcut(a);""!==a&&b.val(a)}};
document.addEventListener("DOMContentLoaded",function(){function b(){var a=/(:)|(\.\.(\\|\/))/.test($("#edtDefaultFolder").val());document.getElementById("spnComment").style.color=a?"#f00":"#666"}try{i18nPrepare()}catch(a){logError(a.message)}$("#btnLicenseInfo").click(function(){getExtension().enterLicense()});$("#btnCapSettings").click(function(){getExtension().openCaptureSettings()});$("#btnGeneralOptions").click(function(){getExtension().openSettings()});$("#btnApply").click(function(){FireShotSettings.saveSettings()});
$("#btnSave").click(function(){FireShotSettings.saveSettings(function(){window.close()})});$("#edtHotkeyLastUsedAction").keydown(function(a){FireShotSettings.processHotkey($(this),a)});$("#edtHotkeyVisible").keydown(function(a){FireShotSettings.processHotkey($(this),a)});$("#edtHotkeyEntire").keydown(function(a){FireShotSettings.processHotkey($(this),a)});$("#edtHotkeySelection").keydown(function(a){FireShotSettings.processHotkey($(this),a)});$("#edtHotkeyBrowser").keydown(function(a){FireShotSettings.processHotkey($(this),
a)});$("#edtHotkeyTabs").keydown(function(a){FireShotSettings.processHotkey($(this),a)});$("#btnTemplateSettings").click(function(){$(this).toggle();$("#divTemplateSettings").toggle()});$("#btnTemplateSettingsHide").click(function(){$("#btnTemplateSettings").toggle();$("#divTemplateSettings").toggle()});$("#btnAdvancedFunctions").click(function(){getExtension().installNative()});$("#btnConfigureHotkeys").click(function(){getExtension().openURL("chrome://extensions/configureCommands")});$("#edtDefaultFolder").change(b);
$("#edtDefaultFolder").keydown(function(){setTimeout(b,100)});(function(){var a=!getExtension().isNativeSupported();$(".native").toggle(!a);$(".lite").toggle(a);$("#fsPro").toggle(a&&isWindows());"true"==localStorage[cRegisteredPref]&&$("#trLicensingInfo").hide();"hpbicldbpgipcloiojdbchegbbjiobbm"==extensionId&&$("#trFSAPI").hide()})();FireShotSettings.loadSettings();b()});
