/*
 FireShot - Webpage Screenshots and Annotations
 Copyright (C) 2007-2020 Evgeny Suslikov (evgeny@suslikov.ru)
*/
var capMode,clickedElem;
function enableToolsItems(){var b=capMode===cModeTabs,c=getExtension().isProMode(),a=b?"block":"none",d=b?"none":"block",e=!c&&b?"disabled":"";document.getElementById("mnuTabsUpgrade").style.display=c||!b?"none":"block";document.getElementById("mnuSaveSinglePDF").style.display=a;document.getElementById("mnuSavePDF").style.display=d;document.getElementById("mnuEdit").className=e;document.getElementById("mnuSave").className=e;document.getElementById("mnuUpload").className=e;document.getElementById("mnuPrint").className=
e;document.getElementById("mnuClipboard").className=e;document.getElementById("mnuEmail").className=e;document.getElementById("mnuExtEdit").className=e;document.getElementById("mnuSendOneNote").className=e;document.getElementById("mnuSaveSinglePDF").className=e}function switchPane(b,c){c=document.getElementById(c);c.style.display="block";c.style.left=Math.min(document.body.clientWidth-c.clientWidth-5,b.pageX)+"px";c.style.top=Math.min(document.body.clientHeight-c.clientHeight-5,b.pageY)+"px"}
function updateLastAction(){var b=getExtension().getLADescription();document.getElementById("spnLastAction").textContent=b;document.getElementById("spnLastAction").title=b;document.getElementById("spnShortcut").textContent="";chrome.commands.getAll(function(c){getLAShortcut(function(a){document.getElementById("spnLastAction").title=b+" ("+a+")";document.getElementById("spnShortcut").textContent=a})})}
function click(b,c){if("disabled"!=b.className){clickedElem=b;capMode===cModeTabs&&b.parentElement&&"mnuTools"===b.parentElement.getAttribute("rel")||"mnuCaptureEntire"==b.id||"mnuCaptureVisible"==b.id||"mnuCaptureSelection"==b.id||"mnuCaptureBrowser"==b.id||"mnuCaptureTabs"==b.id||"mnuMiscellaneousFolder"==b.id||window.close();var a=getExtension(),d=function(a){return capMode!==cModeTabs?a():tabsPermissionRequired(function(){window&&window.close();a()})};switch(b.id){case "mnuResume":a.resumeEditing();
break;case "mnuPreferences":case "mnuPreferencesLite":a.openExtensionPreferences();break;case "mnuQuickLaunch":a.captureLastUsedMode();break;case "mnuCaptureEntire":capMode=cModeEntire;enableToolsItems();switchPane(c,"mnuTools");break;case "mnuCaptureVisible":capMode=cModeVisible;enableToolsItems();switchPane(c,"mnuTools");break;case "mnuCaptureSelection":capMode=cModeSelected;enableToolsItems();switchPane(c,"mnuTools");break;case "mnuCaptureBrowser":capMode=cModeBrowser;enableToolsItems();switchPane(c,
"mnuTools");break;case "mnuCaptureTabs":capMode=cModeTabs;enableToolsItems();switchPane(c,"mnuTools");break;case "mnuMiscellaneousFolder":switchPane(c,"mnuMiscellaneous");break;case "mnuViewDemo":a.openDemoPage();break;case "mnuSupport":a.openSupportPage();break;case "mnuAPI":a.openAPIPage();break;case "mnuTabsUpgrade":case "mnuUpgrade":a.doUpgrade();break;case "mnuRegister":a.doRegister();break;case "mnuEnterLicense":a.enterLicense();break;case "mnuCaptureEntireLite":a.executeGrabber(cActionEdit,
cModeEntire);break;case "mnuCaptureVisibleLite":a.executeGrabber(cActionEdit,cModeVisible);break;case "mnuCaptureSelectionLite":a.executeGrabber(cActionEdit,cModeSelected);break;case "mnuEdit":d(function(){a.executeGrabber(cActionEdit,capMode)});break;case "mnuSave":d(function(){a.executeGrabber(cActionSave,capMode)});break;case "mnuSavePDF":d(function(){a.executeGrabber(cActionSavePDF,capMode)});break;case "mnuSaveSinglePDF":d(function(){a.executeGrabber(cActionMultiPDF,capMode)});break;case "mnuUpload":d(function(){a.executeGrabber(cActionUpload,
capMode)});break;case "mnuPrint":d(function(){a.executeGrabber(cActionPrint,capMode)});break;case "mnuClipboard":d(function(){a.executeGrabber(cActionClipboard,capMode)});break;case "mnuEmail":d(function(){a.executeGrabber(cActionEMail,capMode)});break;case "mnuExtEdit":d(function(){a.executeGrabber(cActionPaint,capMode)});break;case "mnuSendOneNote":d(function(){a.executeGrabber(cActionSendOneNote,capMode)});break;case "mnuOpenFile":a.openFile();break;case "mnuOpenClipboard":a.openClipboard();break;
case "mnuLicenseInfo":a.showLicenseInfo();break;case "mnuAbout":a.showAbout();break;case "mnuFireShotNative":a.installNative();break;case "lnkDuplicateTab":a.duplicateTab();break;case "lnkTryAnotherPage":window.close();a.openURL("https://www.google.com/search?q=kitties");break;case "lnkAllowFileAccess":a.openURL("https://getfireshot.com/enable-file-access.php?browser=ch");break;case "lnkExtensionSettings":a.openExtensionSettings()}}}
function mouseOver(b,c){b==clickedElem||b.parentNode&&"mnuTools"==b.parentNode.getAttribute("rel")||(document.getElementById("mnuTools").style.display="none");b==clickedElem||b.parentNode&&"mnuMiscellaneous"==b.parentNode.getAttribute("rel")||(document.getElementById("mnuMiscellaneous").style.display="none")}
function load(){try{i18nPrepare()}catch(e){logError(e.message)}for(var b=document.createNodeIterator(document.documentElement,NodeFilter.SHOW_ELEMENT,null,!1),c,a=function(a){a.preventDefault();click(this,a);return!0},d=function(a){mouseOver(this,a)};c=b.nextNode();)if("LI"==c.nodeName||"command"===c.getAttribute("rel"))c.onclick=a,c.onmouseover=d;updateLastAction();updateAccessibility()}
function updateAccessibility(){getExtension().checkAdvancedFeatures();getExtension().getMenuSettings(function(b){for(var c in b){var a=document.getElementById(c);if(null===a)alert("Element "+c+" not found");else{var d=b[c];a.style.display="hidden"===d?"none":"block";"disabled"===d?a.classList.add("disabled"):a.classList.remove("disabled")}}document.body.style.display="block"})}
document.addEventListener("DOMContentLoaded",function(){var b=getExtension();b.checkActivationPage(function(b){b&&window.close()});b.checkBadgeAction()?window.close():load()});
